[production]
secret_key = "2zau6Td7HmXhWmrblS8q/e/Fqhb+IZPlZ8tNO07hhQI="
log = "critical"
address = "0.0.0.0"
port = 8888
num_tables = 100
max_table_items = 1000
one_min_in_sec = 1

[development]
log = "normal"
address = "0.0.0.0"
port = 8888
num_tables = 100
max_table_items = 1000
one_min_in_sec = 1